# Generated by Django 5.2.7 on 2025-10-10 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=50)),
                ('tier_percentage_start', models.IntegerField()),
                ('tier_percentage_end', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_price_tiers', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='events.event')),
            ],
            options={
                'ordering': ['event', 'tier_percentage_start'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('tickets_sold_count', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='events.event')),
                ('new_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_price_history', to='pricing.pricetier')),
                ('old_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_price_history', to='pricing.pricetier')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pricetier',
            index=models.Index(fields=['event', 'is_active'], name='pricing_pri_event_i_b0ada4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricetier',
            unique_together={('event', 'tier_percentage_start', 'tier_percentage_end')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['event', 'changed_at'], name='pricing_pri_event_i_2f078d_idx'),
        ),
    ]
