# Generated by Django 5.2.7 on 2025-11-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_split_artist_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='artist',
            new_name='artists_art_first_n_c7b023_idx',
            old_name='artists_art_first_n_72bf1f_idx',
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
