# Generated by Django 5.2.7 on 2025-10-12 15:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('artists', '0002_album_track_artist_followers_artist_popularity_and_more'),
        ('customers', '0002_alter_feedback_rating'),
        ('events', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('play', 'Play'), ('like', 'Like'), ('share', 'Share'), ('playlist_add', 'Added to Playlist'), ('download', 'Download')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date']},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='customers_b_custome_9d0ca0_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='customers_b_event_i_318d21_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='customers_b_booking_a280a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_c_user_id_c1d57c_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='customers_f_event_i_c813ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='customers_f_created_354a1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='customers_t_status_fd09f3_idx',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='payment_reference',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='marketing_consent',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='preferred_artists',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='preferred_genres',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='would_recommend',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='section',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='customers.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='events.event'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', '-booking_date'], name='customers_b_custome_a0f133_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['event', 'payment_status'], name='customers_b_event_i_b946cc_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['city', 'country'], name='customers_c_city_2f324a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['event', '-rating'], name='customers_f_event_i_75cd38_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_at'], name='customers_f_created_37940b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['booking'], name='customers_t_booking_735a60_idx'),
        ),
        migrations.AddField(
            model_name='faninteraction',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='faninteraction',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_interactions', to='artists.track'),
        ),
        migrations.AddIndex(
            model_name='faninteraction',
            index=models.Index(fields=['fan', 'track', 'timestamp'], name='customers_f_fan_id_cb3d82_idx'),
        ),
        migrations.AddIndex(
            model_name='faninteraction',
            index=models.Index(fields=['track', '-timestamp'], name='customers_f_track_i_5146f0_idx'),
        ),
        migrations.AddIndex(
            model_name='faninteraction',
            index=models.Index(fields=['interaction_type', '-timestamp'], name='customers_f_interac_d55161_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='faninteraction',
            unique_together={('fan', 'track', 'timestamp', 'interaction_type')},
        ),
    ]
