# Generated by Django 5.2.7 on 2025-10-12 16:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_album_track_artist_followers_artist_popularity_and_more'),
        ('customers', '0003_faninteraction_alter_booking_options_and_more'),
        ('events', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='customers_b_custome_a0f133_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='customers_b_event_i_b946cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_c_city_2f324a_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='customers_f_event_i_75cd38_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='customers_f_created_37940b_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='customers_t_booking_735a60_idx',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='transaction_id',
            new_name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='tickets',
            field=models.ManyToManyField(related_name='bookings', to='customers.ticket'),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_artists',
            field=models.ManyToManyField(blank=True, to='artists.artist'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_genres',
            field=models.ManyToManyField(blank=True, to='artists.genre'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='customers.booking'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='would_recommend',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='section',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faninteraction',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='events.event'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'booking_date'], name='customers_b_custome_9d0ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['event', 'status'], name='customers_b_event_i_318d21_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='customers_b_booking_a280a3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user'], name='customers_c_user_id_c1d57c_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['country'], name='customers_c_country_fc020b_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['event', 'rating'], name='customers_f_event_i_c813ab_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['created_at'], name='customers_f_created_354a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='customers_t_status_fd09f3_idx'),
        ),
    ]
