"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file in core directory
load_dotenv(os.path.join(BASE_DIR, 'core', '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k+)%kez=6im9xnd2q@wye7pq7g#_6oo#d!h&!n3q3&%@as18_^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'jazzmin',

    # Local apps
    'accounts',
    'artists',
    'events',
    'customers',
    'pricing',
    'analytics',
    'search',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add custom templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'rhythmlink_db',
        'USER': 'postgres',
        'PASSWORD': os.getenv('PASSWORD'),  # Default to 'postgres' if env var not set
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Custom settings for role-based permissions
ROLE_PERMISSIONS = {
    'manager': [
        'events.add_event',
        'events.change_event',
        'events.delete_event',
        'pricing.add_pricetier',
        'pricing.change_pricetier',
        'analytics.view_eventanalytics',
    ],
    'customer': [
        'customers.add_booking',
        'customers.change_booking',
        'customers.add_feedback',
    ]
}

# ==================== JAZZMIN CONFIGURATION ====================

JAZZMIN_SETTINGS = {
    # Title on the login screen & admin
    "site_title": "RhythmLink Admin",
    "site_header": "RhythmLink",
    "site_brand": "RhythmLink - Event Management",
    "site_logo": None,  # Add path to your logo: "images/logo.png"
    "login_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to RhythmLink Admin Dashboard",
    
    # Copyright on the footer
    "copyright": "RhythmLink - Artist & Event Management System",
    
    # Links to put along the top menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
        {"name": "API Docs", "url": "/api/", "new_window": True},
        {"model": "auth.User"},
        {"app": "events"},
    ],
    
    # User menu on the top right
    "usermenu_links": [
        {"name": "View Site", "url": "/", "new_window": True},
        {"model": "auth.user"},
    ],
    
    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    
    # Order of apps & models in the side menu
    "order_with_respect_to": [
        "auth",
        "accounts",
        "artists",
        "events",
        "customers",
        "pricing",
        "analytics",
        "search",
    ],
    
    # Custom icons for models
    "icons": {
        # Auth
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # Accounts
        "accounts.UserProfile": "fas fa-user-circle",
        
        # Artists
        "artists.Genre": "fas fa-music",
        "artists.Artist": "fas fa-microphone",
        "artists.Album": "fas fa-compact-disc",
        "artists.Track": "fas fa-headphones",
        
        # Events
        "events.Event": "fas fa-calendar-alt",
        "events.Venue": "fas fa-map-marker-alt",
        "events.EventType": "fas fa-tags",
        "events.Performs": "fas fa-guitar",
        "events.EventManager": "fas fa-user-tie",
        
        # Customers
        "customers.Customer": "fas fa-user-friends",
        "customers.Booking": "fas fa-ticket-alt",
        "customers.Ticket": "fas fa-receipt",
        "customers.Feedback": "fas fa-star",
        "customers.FanInteraction": "fas fa-heart",
        
        # Pricing
        "pricing.PriceTier": "fas fa-layer-group",
        "pricing.PriceHistory": "fas fa-history",
        
        # Analytics
        "analytics.EventAnalytics": "fas fa-chart-line",
        "analytics.DashboardSnapshot": "fas fa-camera",
        "analytics.ManagerDashboardConfig": "fas fa-cog",
        
        # Search
        "search.SearchHistory": "fas fa-search",
        "search.PopularSearches": "fas fa-fire",
    },
    
    # Icons for default apps
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # Related modal (change_form)
    "related_modal_active": False,
    
    # Use modals instead of popups
    "custom_css": None,
    "custom_js": None,
    
    # Show a language chooser
    "show_ui_builder": False,
    
    # Change view settings
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs"
    },
    
    # Language chooser
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark navbar-primary",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",  # Options: default, cerulean, cosmo, cyborg, darkly, flatly, journal, litera, lumen, lux, materia, minty, pulse, sandstone, simplex, sketchy, slate, solar, spacelab, superhero, united, yeti
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False,
}
