# Generated by Django 5.2.7 on 2025-10-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('total_tracks', models.IntegerField(default=0)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='albums/')),
                ('description', models.TextField(blank=True)),
                ('spotify_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.IntegerField()),
                ('track_name', models.CharField(max_length=200)),
                ('duration_ms', models.IntegerField(help_text='Duration in milliseconds')),
                ('spotify_url', models.URLField(blank=True)),
                ('preview_url', models.URLField(blank=True)),
                ('is_explicit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['album', 'track_number'],
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['-popularity'], name='artists_art_popular_2d59f2_idx'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='artists.album'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', '-release_date'], name='artists_alb_artist__921dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['album_name'], name='artists_alb_album_n_42d4ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('artist', 'album_name')},
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['album', 'track_number'], name='artists_tra_album_i_b4df86_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['track_name'], name='artists_tra_track_n_6928f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('album', 'track_number')},
        ),
    ]
